#!/usr/bin/env python3
"""Translate Vietnamese UI strings in static frontend files to English."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "static"

# Longest-first replacements to avoid partial matches
TRANSLATIONS = [
    # Meta / lang
    ('lang="vi"', 'lang="en"'),
    ("pageLanguage: 'vi'", "pageLanguage: 'en'"),
    ("toLocaleDateString('vi-VN')", "toLocaleDateString('en-US')"),
    ("toLocaleString('vi-VN')", "toLocaleString('en-US')"),
    ("NumberFormat('vi-VN').format(v) + ' ₫'", "NumberFormat('en-IN').format(v) + ' ₹'"),
    ("Register ngay", "Register now"),
    # index.html
    ("AI Legal Agent — Trợ lý pháp lý thông minh cho doanh nghiệp", "AI Legal Agent — Smart Legal Assistant for Businesses"),
    ("Search 40,000+ văn bản pháp luật, rà soát hợp đồng, soạn văn bản pháp lý bằng AI.", "Search 40,000+ legal documents, review contracts, and draft legal documents with AI."),
    ("Tính năng", "Features"),
    ("Cách hoạt động", "How It Works"),
    ("Bảng giá", "Pricing"),
    ("tài liệu pháp luật", "legal documents"),
    ("công cụ AI", "AI tools"),
    ("sẵn sàng", "available"),
    ("Mọi thứ bạn cần trong một nền tảng", "Everything you need in one platform"),
    ("Chat AI Pháp Lý", "Legal AI Chat"),
    ("Hỏi bất kỳ câu hỏi pháp lý, nhận câu trả lời có trích dẫn luật cụ thể từ 60,000+ tài liệu", "Ask any legal question and get answers with specific law citations from 60,000+ documents"),
    ("Rà soát Hợp đồng AI", "AI Contract Review"),
    ("Upload hợp đồng, AI phân tích rủi ro, điều khoản thiếu, và tuân thủ pháp luật India", "Upload contracts — AI analyzes risks, missing clauses, and India law compliance"),
    ("Tích hợp đa nhà cung cấp: Anthropic Claude, OpenAI GPT, Google Gemini — tự do chọn lựa", "Multi-provider integration: Anthropic Claude, OpenAI GPT, Google Gemini — choose freely"),
    ("Risk Overview tất cả hợp đồng, cảnh báo hết hạn, compliance tracking", "Risk overview for all contracts, expiry alerts, compliance tracking"),
    ("24 Công cụ AI", "24 AI Tools"),
    ("Soạn hợp đồng, giải thích điều khoản, so sánh văn bản, tạo tóm tắt, và nhiều hơn nữa", "Draft contracts, explain clauses, compare documents, generate summaries, and more"),
    ("Analytics sử dụng, top câu hỏi, performance tracking, và báo cáo chi tiết", "Usage analytics, top questions, performance tracking, and detailed reports"),
    ("3 bước đơn giản", "3 simple steps"),
    ("Từ đăng ký đến kết quả — nhanh chóng và dễ dàng", "From sign-up to results — fast and easy"),
    ("Register tài khoản", "Create an account"),
    ("Tạo tài khoản miễn phí, không cần thẻ tín dụng", "Create a free account — no credit card required"),
    ("Upload hợp đồng hoặc hỏi AI", "Upload a contract or ask AI"),
    ("Tải lên hợp đồng cần rà soát hoặc đặt câu hỏi pháp lý", "Upload a contract for review or ask a legal question"),
    ("Nhận phân tích chi tiết", "Get detailed analysis"),
    ("AI trả lời với trích dẫn luật và đề xuất hành động cụ thể", "AI responds with law citations and specific action recommendations"),
    ("Chọn gói phù hợp", "Choose the right plan"),
    ("Get Started for free, nâng cấp khi cần", "Get started for free, upgrade when you need"),
    ("Miễn phí", "Free"),
    ("Get Started ngay", "Get started now"),
    ("10 câu hỏi / ngày", "10 questions / day"),
    ("3 hợp đồng", "3 contracts"),
    ("Rà soát AI nâng cao", "Advanced AI review"),
    ("Xuất báo cáo", "Export reports"),
    ("Phổ biến nhất", "Most popular"),
    ("/ tháng", "/ month"),
    ("100 câu hỏi / ngày", "100 questions / day"),
    ("Không giới hạn hợp đồng", "Unlimited contracts"),
    ("Xuất báo cáo PDF", "PDF report export"),
    ("Hỗ trợ ưu tiên", "Priority support"),
    ("Dùng thử 14 ngày →", "Try 14 days free →"),
    ("Tùy chỉnh theo nhu cầu", "Custom pricing"),
    ("Không giới hạn câu hỏi", "Unlimited questions"),
    ("SSO & bảo mật nâng cao", "SSO & advanced security"),
    ("Contact tư vấn", "Contact sales"),
    ("Sẵn sàng số hóa pháp lý doanh nghiệp?", "Ready to digitize your legal operations?"),
    ("Get Started for free ngay hôm nay. Không cần thẻ tín dụng.", "Get started for free today. No credit card required."),
    # platform-admin
    ("Công ty", "Companies"),
    ("Người dùng", "Users"),
    ("Bảo trì", "Maintenance"),
    ("🔄 Làm mới", "🔄 Refresh"),
    ("Tổng công ty", "Total Companies"),
    ("Đang hoạt động", "Active"),
    ("đang hoạt động", "active"),
    ("Tài liệu", "Documents"),
    ("hợp đồng", "contracts"),
    ("Queries hôm nay", "Queries Today"),
    ("trong tháng", "this month"),
    ("Luật VN", "Indian Laws"),
    ("Usage Trend (30 ngày)", "Usage Trend (30 days)"),
    ("Top Công ty", "Top Companies"),
    ("Đang tải...", "Loading..."),
    ("Tìm kiếm công ty...", "Search companies..."),
    ("🔍 Tìm kiếm", "🔍 Search"),
    ("Danh sách công ty", "Company List"),
    ("Tạo ngày", "Created"),
    ("Trạng thái", "Status"),
    ("Hành động", "Actions"),
    ("Tìm người dùng...", "Search users..."),
    ("Danh sách người dùng", "User List"),
    ("Tên", "Name"),
    ("Đăng nhập cuối", "Last Login"),
    ("Settings hệ thống", "System Settings"),
    ("Cho phép đăng ký", "Allow registration"),
    ("Chế độ bảo trì", "Maintenance mode"),
    ("Thông báo bảo trì", "Maintenance message"),
    ("Hệ thống đang bảo trì...", "System is under maintenance..."),
    ("💾 Lưu cài đặt", "💾 Save Settings"),
    ("Delete dữ liệu cũ (>30 ngày)", "Delete old data (>30 days)"),
    ("Chỉnh sửa công ty", "Edit Company"),
    ("Kích hoạt", "Activate"),
    ("Hủy", "Cancel"),
    ("Lưu", "Save"),
    ("Bạn không có quyền truy cập Platform Admin", "You do not have access to Platform Admin"),
    ("Chưa có dữ liệu", "No data yet"),
    ("Lỗi tải dashboard: ", "Error loading dashboard: "),
    ("Không tìm thấy công ty", "No companies found"),
    ("✏️ Sửa", "✏️ Edit"),
    ("Lỗi tải danh sách công ty: ", "Error loading company list: "),
    ("Đã cập nhật công ty", "Company updated"),
    ("Lỗi cập nhật: ", "Update error: "),
    ("Không tìm thấy người dùng", "No users found"),
    ("Chưa đăng nhập", "Never logged in"),
    ("⛔ Vô hiệu", "⛔ Deactivate"),
    ("✅ Kích hoạt", "✅ Activate"),
    ("Lỗi tải danh sách người dùng: ", "Error loading user list: "),
    ("Đã cập nhật trạng thái", "Status updated"),
    ("Lỗi: ", "Error: "),
    ("Lỗi tải cài đặt: ", "Error loading settings: "),
    ("Đã lưu cài đặt", "Settings saved"),
    ("Lỗi lưu cài đặt: ", "Error saving settings: "),
    ("Lỗi tải LLM usage: ", "Error loading LLM usage: "),
    ("Chưa có logs", "No logs yet"),
    ("Lỗi tải logs: ", "Error loading logs: "),
    ("Lỗi tải DB stats: ", "Error loading DB stats: "),
    ("Delete tất cả hợp đồng đã xóa >30 ngày?", "Delete all contracts soft-deleted >30 days ago?"),
    ("Lỗi cleanup: ", "Cleanup error: "),
    ("section.includes('công ty')", "section.includes('companies')"),
    ("section.includes('người dùng')", "section.includes('users')"),
    ("section.includes('cài đặt')", "section.includes('settings')"),
    ("section.includes('bảo trì')", "section.includes('maintenance')"),
    # app.html - CSS content
    ("content: '📎 Thả file vào đây'", "content: '📎 Drop file here'"),
    # Sidebar / explorer
    ("title=\"Ẩn\"", "title=\"Hide\""),
    ("＋ Tải lên hợp đồng", "＋ Upload contract"),
    ("TÀI LIỆU", "DOCUMENTS"),
    ("＋ Tải lên tài liệu", "＋ Upload document"),
    ("MẪU VĂN BẢN", "TEMPLATES"),
    ("🔍 Tìm điều luật, nghị định...", "🔍 Search laws, regulations..."),
    ("Nghị Định", "Ordinance"),
    ("Thông Tư", "Circular"),
    ("Nhập từ khóa và nhấn Enter", "Enter keywords and press Enter"),
    ("➕ Cuộc hội thoại mới", "➕ New conversation"),
    ("Tìm kiếm...", "Search..."),
    ("Tháng ", "Month "),
    ("📊 Risk Overview hợp đồng", "📊 Contract Risk Overview"),
    ("📈 Analytics sử dụng", "📈 Usage Analytics"),
    ("7 ngày", "7 days"),
    ("30 ngày", "30 days"),
    ("90 ngày", "90 days"),
    ("Tổng câu hỏi", "Total questions"),
    ("TB thời gian", "Avg. response time"),
    ("Có trích dẫn", "With citations"),
    ("Lượt sử dụng theo ngày", "Daily usage"),
    ("Câu hỏi phổ biến", "Popular questions"),
    ("Hợp đồng", "Contracts"),
    ("Mẫu văn bản", "Templates"),
    ("Upload hợp đồng", "Upload contract"),
    ("Tải lên và phân tích AI", "Upload and analyze with AI"),
    ("Tạo mẫu văn bản", "Create from template"),
    ("Soạn thảo từ template", "Draft from template"),
    ("Tìm kiếm văn bản pháp luật", "Search legal documents"),
    ("API & Tích hợp", "API & Integrations"),
    ("Kết nối Legal AI API", "Connect to Legal AI API"),
    ("So sánh hợp đồng", "Compare contracts"),
    ("So sánh nội dung, điều khoản", "Compare content and clauses"),
    ("Xem rủi ro hợp đồng", "View contract risks"),
    ("Analytics sử dụng", "Usage analytics"),
    ("Phân tích hoạt động", "Activity analysis"),
    ("Đang tải gợi ý...", "Loading suggestions..."),
    ("Kết nối", "Connected"),
    ("Sẵn sàng", "Ready"),
    ("title=\"Thông báo\"", "title=\"Notifications\""),
    ("title=\"Xuất chat\"", "title=\"Export chat\""),
    ("title=\"Chat mới\"", "title=\"New chat\""),
    ("Xin chào! 👋", "Hello! 👋"),
    ("Phân tích hợp đồng lao động của tôi", "Analyze my employment contract"),
    ("⚖️ Phân tích hợp đồng lao động", "⚖️ Analyze employment contract"),
    ("Search quy định về nghỉ phép năm", "Search annual leave regulations"),
    ("🔍 Search quy định nghỉ phép", "🔍 Search leave regulations"),
    ("Liệt kê tất cả hợp đồng đang có", "List all my contracts"),
    ("📋 Liệt kê hợp đồng", "📋 List contracts"),
    ("Soạn hợp đồng dịch vụ", "Draft a service agreement"),
    ("✍️ Soạn hợp đồng dịch vụ", "✍️ Draft service agreement"),
    ("title=\"Đính kèm\"", "title=\"Attach file\""),
    ("Hỏi bất kỳ câu hỏi pháp lý nào... (Ctrl+K lệnh nhanh)", "Ask any legal question... (Ctrl+K quick commands)"),
    ("Tải lên hợp đồng", "Upload contract"),
    ("File hợp đồng (PDF, DOCX, hoặc ảnh)", "Contract file (PDF, DOCX, or image)"),
    ("Kéo thả hoặc <span style=\"color: var(--accent); cursor: pointer;\" onclick=\"document.getElementById('contractFile').click()\">chọn file</span>", "Drag & drop or <span style=\"color: var(--accent); cursor: pointer;\" onclick=\"document.getElementById('contractFile').click()\">choose file</span>"),
    ("AI sẽ tự động quét và điền thông tin", "AI will automatically scan and fill in details"),
    ("🤖 AI đang phân tích...", "🤖 AI is analyzing..."),
    ("✅ AI đã điền thông tin", "✅ AI filled in details"),
    ("Tên hợp đồng", "Contract name"),
    ("AI sẽ tự động điền...", "AI will auto-fill..."),
    ("Loại hợp đồng", "Contract type"),
    ("Chọn loại", "Select type"),
    ("Hợp đồng lao động", "Employment contract"),
    ("Hợp đồng dịch vụ", "Service contract"),
    ("Hợp đồng thuê", "Lease contract"),
    ("Hợp đồng mua bán", "Sale contract"),
    ("Hợp đồng hợp tác", "Partnership contract"),
    ("Khác", "Other"),
    ("Các bên tham gia", "Parties"),
    ("Ngày bắt đầu", "Start date"),
    ("Ngày kết thúc", "End date"),
    ("Giá trị (VNĐ)", "Value (INR)"),
    ("📝 Tóm tắt AI", "📝 AI Summary"),
    ("📤 Tải lên", "📤 Upload"),
    ("Chi tiết hợp đồng", "Contract details"),
    ("Kết quả rà soát AI", "AI Review Results"),
    ("Chào mừng đến với AI Legal Agent!", "Welcome to AI Legal Agent!"),
    ("Hoàn thành các bước sau để bắt đầu", "Complete these steps to get started"),
    ("0/6 bước", "0/6 steps"),
    ("/6 bước", "/6 steps"),
    (" bước", " steps"),
    ("Bỏ qua", "Skip"),
    ("Get Started sử dụng →", "Get started →"),
    ("⌨️ Phím tắt", "⌨️ Keyboard Shortcuts"),
    ("Gửi tin nhắn", "Send message"),
    ("Xuống dòng", "New line"),
    ("Chat mới", "New chat"),
    ("Đóng modal", "Close modal"),
    ("/ra-soat", "/review"),
    ("Rà soát HĐ", "Review contract"),
    ("👤 Thông tin cá nhân", "👤 Personal Information"),
    ("💾 Lưu thông tin", "💾 Save profile"),
    ("🏢 Thông tin công ty", "🏢 Company Information"),
    ("Mã số thuế", "Tax ID"),
    ("Địa chỉ", "Address"),
    ("123 Nguyễn Huệ, Q1, TP.HCM", "123 Main Street, Mumbai"),
    ("💾 Lưu công ty", "💾 Save company"),
    ("🎨 Giao diện", "🎨 Appearance"),
    ("Chế độ tối / sáng", "Dark / light mode"),
    ("🔔 Thông báo", "🔔 Notifications"),
    ("Hợp đồng sắp hết hạn", "Contracts expiring soon"),
    ("AI hoàn thành rà soát", "AI review completed"),
    ("Update luật mới", "New law updates"),
    ("💾 Lưu thông báo", "💾 Save notification preferences"),
    ("Nhà cung cấp", "Provider"),
    ("title=\"Hiện/Ẩn\"", "title=\"Show/Hide\""),
    ("🔗 Kết nối với OpenAI", "🔗 Connect with OpenAI"),
    ("🔗 Kết nối với Google", "🔗 Connect with Google"),
    ("💾 Lưu cấu hình", "💾 Save configuration"),
    ("🔌 Test kết nối", "🔌 Test connection"),
    ("📦 Dữ liệu", "📦 Data"),
    ("📥 Xuất tất cả dữ liệu", "📥 Export all data"),
    ("💬 Xuất lịch sử chat", "💬 Export chat history"),
    ("📄 Xuất hợp đồng", "📄 Export contracts"),
    ("🔐 Tài khoản", "🔐 Account"),
    ("Gói dịch vụ:", "Plan:"),
    ("Câu hỏi còn lại:", "Questions remaining:"),
    ("Ngày đăng ký:", "Registered:"),
    ("⬆️ Nâng cấp", "⬆️ Upgrade"),
    ("🚪 Đăng xuất", "🚪 Log out"),
    ("📦 Upload nhiều hợp đồng", "📦 Batch upload contracts"),
    ("Kéo thả files vào đây hoặc", "Drag & drop files here or"),
    ("Chọn files", "Choose files"),
    ("PDF, DOCX, TXT — Tối đa 10 files, mỗi file ≤ 10MB", "PDF, DOCX, TXT — Max 10 files, 10MB each"),
    ("0 files đã chọn", "0 files selected"),
    (" files đã chọn", " files selected"),
    ("📤 Upload tất cả", "📤 Upload all"),
    ("'hop_dong': 'Hợp đồng', 'hanh_chinh': 'Hành chính', 'noi_bo': 'Nội bộ'", "'hop_dong': 'Contracts', 'hanh_chinh': 'Administrative', 'noi_bo': 'Internal'"),
    ("'read_contract': { icon: '📄', label: 'Đọc hợp đồng' }", "'read_contract': { icon: '📄', label: 'Read contract' }"),
    ("'list_contracts': { icon: '📋', label: 'Liệt kê hợp đồng' }", "'list_contracts': { icon: '📋', label: 'List contracts' }"),
    ("'search_company_docs': { icon: '📂', label: 'Tìm tài liệu công ty' }", "'search_company_docs': { icon: '📂', label: 'Search company documents' }"),
    ("'analyze_contract_risk': { icon: '⚠️', label: 'Phân tích rủi ro' }", "'analyze_contract_risk': { icon: '⚠️', label: 'Analyze risk' }"),
    ("'draft_document': { icon: '✍️', label: 'Soạn thảo văn bản' }", "'draft_document': { icon: '✍️', label: 'Draft document' }"),
    ("'get_company_profile': { icon: '🏢', label: 'Lấy thông tin công ty' }", "'get_company_profile': { icon: '🏢', label: 'Get company profile' }"),
    ("'compare_contracts': { icon: '⚖️', label: 'So sánh hợp đồng' }", "'compare_contracts': { icon: '⚖️', label: 'Compare contracts' }"),
    ("'Đang ' + meta.label.toLowerCase() + '...'", "'Running ' + meta.label.toLowerCase() + '...'"),
    (" kết quả", " results"),
    ("Chưa có hợp đồng", "No contracts yet"),
    ("'HĐ'", "'Contract'"),
    ("Chưa đặt tên", "Untitled"),
    ("Chưa có tài liệu", "No documents yet"),
    ("'Mẫu văn bản'", "'Templates'"),
    ("'Rà soát Hợp đồng'", "'Contract Review'"),
    ("🔍 Rà soát Hợp đồng", "🔍 Contract Review"),
    ("🔍 Tìm kiếm", "🔍 Search"),
    ("'Hợp đồng'", "'Contract'"),
    ("<strong>Trang:</strong>", "<strong>Pages:</strong>"),
    ("title=\"Chọn để so sánh\"", "title=\"Select to compare\""),
    ("title=\"Xem\"", "title=\"View\""),
    ("Get Started rà soát", "Start review"),
    ("Chưa xác định", "Not specified"),
    ("Các bên", "Parties"),
    ("Không có tổng quan.", "No overview available."),
    ("✅ Không phát hiện điều khoản có vấn đề", "✅ No problematic clauses detected"),
    ("💡 Đề xuất sửa đổi:", "💡 Suggested revision:"),
    ("title=\"Sao chép\"", "title=\"Copy\""),
    ("'Bộ Law Dân Sự 2015': 'PASS'", "'Indian Contract Act 1872': 'PASS'"),
    ("'Law Thương Mại 2005': 'PASS'", "'Companies Act 2013': 'PASS'"),
    ("'Bộ Law Lao Động 2019': 'UNKNOWN'", "'Industrial Disputes Act 1947': 'UNKNOWN'"),
    ("'Law Doanh Nghiệp 2020': 'PASS'", "'Partnership Act 1932': 'PASS'"),
    ("'Tuân thủ'", "'Compliant'"),
    ("'Không tuân thủ'", "'Non-compliant'"),
    ("'Chưa rõ'", "'Unknown'"),
    ("Không có khuyến nghị đặc biệt.", "No special recommendations."),
    ("Đã sao chép!", "Copied!"),
    ("Không thể sao chép", "Could not copy"),
    ("'Thành công'", "'Success'"),
    ("'Lỗi'", "'Error'"),
    ("'Cảnh báo'", "'Warning'"),
    ("'Thông báo'", "'Notice'"),
    ("Login thành công!", "Login successful!"),
    ("Email hoặc mật khẩu không đúng", "Invalid email or password"),
    ("Có lỗi xảy ra", "Something went wrong"),
    ("Register thành công!", "Registration successful!"),
    ("Register thất bại", "Registration failed"),
    ("Đăng xuất?", "Log out?"),
    ("Đã đăng xuất", "Logged out"),
    ("Chưa có lịch sử", "No history yet"),
    ("Hôm qua", "Yesterday"),
    ("7 ngày trước", "Last 7 days"),
    ("Cũ hơn", "Older"),
    ("Cuộc hội thoại mới", "New conversation"),
    (" tin nhắn", " messages"),
    ("Rà soát file:", "Review file:"),
    ("Đang đọc file...", "Reading file..."),
    ("Đang tìm kiếm...", "Searching..."),
    ("Không thể đọc file", "Could not read file"),
    ("Đang phân tích...", "Analyzing..."),
    ("Lỗi upload file", "File upload error"),
    ("Không thể upload file", "Could not upload file"),
    ("Lỗi ${response.status}", "Error ${response.status}"),
    ("Vào **Settings → AI Provider** để nhập API key của bạn.", "Go to **Settings → AI Provider** to enter your API key."),
    ("Thử lại.", "Please try again."),
    ("Không thể kết nối", "Could not connect"),
    ("Không thể kết nối. Thử lại.", "Could not connect. Please try again."),
    ("**Lỗi:**", "**Error:**"),
    (" nguồn", " sources"),
    ("title=\"Hữu ích\"", "title=\"Helpful\""),
    ("title=\"Không hữu ích\"", "title=\"Not helpful\""),
    ("Đã sao chép", "Copied"),
    ("Đã tải Word", "Word downloaded"),
    ("Lỗi xuất Word", "Word export error"),
    ("Cảm ơn!", "Thank you!"),
    ("... (hiển thị 100 dòng đầu, tải xuống để xem đầy đủ)", "... (showing first 100 lines, download for full content)"),
    (" thêm, ", " added, "),
    (" xóa", " removed"),
    (" thay đổi (", " changes ("),
    ("📥 Tải xuống file Word (.docx)", "📥 Download Word file (.docx)"),
    ("📥 Tải xuống bản đã sửa (TXT)", "📥 Download edited version (TXT)"),
    ("❌ Đóng", "❌ Close"),
    ("Đã tải xuống: ", "Downloaded: "),
    ("Lỗi khi tải xuống file", "Error downloading file"),
    ("Chỉ hỗ trợ PDF, DOCX, DOC, TXT", "Only PDF, DOCX, DOC, TXT supported"),
    ("File quá lớn (max 10MB)", "File too large (max 10MB)"),
    ("-- Chọn --", "-- Select --"),
    ("⚖️ Tạo văn bản", "⚖️ Generate document"),
    ("Văn bản đã tạo!", "Document created!"),
    ("Không thể tạo", "Could not create"),
    ("📋 Sao chép", "📋 Copy"),
    ("Đóng", "Close"),
    ("'active': 'Hiệu lực', 'pending': 'Sắp hết hạn', 'expired': 'Hết hạn', 'uploaded': 'Đã tải lên', 'processed': 'Đã xử lý', 'analyzed': 'Đã phân tích', 'pending_ocr': 'Chờ OCR'", "'active': 'Active', 'pending': 'Expiring soon', 'expired': 'Expired', 'uploaded': 'Uploaded', 'processed': 'Processed', 'analyzed': 'Analyzed', 'pending_ocr': 'Pending OCR'"),
    ("'hop_dong_lao_dong': 'Lao động', 'hop_dong_dich_vu': 'Dịch vụ', 'hop_dong_thue': 'Thuê', 'hop_dong_mua_ban': 'Mua bán', 'hop_dong_hop_tac': 'Hợp tác', 'khac': 'Khác'", "'hop_dong_lao_dong': 'Employment', 'hop_dong_dich_vu': 'Service', 'hop_dong_thue': 'Lease', 'hop_dong_mua_ban': 'Sale', 'hop_dong_hop_tac': 'Partnership', 'khac': 'Other'"),
    ("Không thể phân tích", "Could not analyze"),
    ("'low': 'Thấp', 'medium': 'Trung bình', 'high': 'Cao'", "'low': 'Low', 'medium': 'Medium', 'high': 'High'"),
    ("Không có nội dung", "No content"),
    ("⚠️ Vấn đề (", "⚠️ Issues ("),
    ("💡 Đề xuất", "💡 Recommendations"),
    ("📥 Xuất báo cáo", "📥 Export report"),
    ("📄 Hợp đồng gốc", "📄 Original contract"),
    ("🔍 Kết quả phân tích", "🔍 Analysis results"),
    ("Mức độ rủi ro", "Risk level"),
    ("📝 Tóm tắt", "📝 Summary"),
    ("Không có", "N/A"),
    ("Không có dữ liệu", "No data"),
    ("BÁO CÁO RÀ SOÁT CONTRACTS", "CONTRACT REVIEW REPORT"),
    ("Ngày:", "Date:"),
    ("Rủi ro:", "Risk:"),
    ("Tóm tắt:", "Summary:"),
    ("Vấn đề:", "Issues:"),
    ("Đề xuất:", "Recommendations:"),
    ("'Văn bản'", "'Document'"),
    ("📖 Xem đầy đủ", "📖 View full text"),
    ("💬 Hỏi AI", "💬 Ask AI"),
    ("Chọn ít nhất 2 hợp đồng", "Select at least 2 contracts"),
    ("🏆 Hợp đồng có lợi nhất", "🏆 Best contract for company"),
    ("Xem", "View"),
    ("Thêm ghi chú...", "Add a note..."),
    ("Thêm ghi chú", "Add note"),
    ("Nhập nội dung ghi chú", "Enter note content"),
    ("'/so-sanh', icon: '⚖️', desc: 'So sánh hợp đồng'", "'/compare', icon: '⚖️', desc: 'Compare contracts'"),
    ("'/mau', icon: '📋', desc: 'Tạo mẫu văn bản'", "'/template', icon: '📋', desc: 'Create from template'"),
    ("'/moi', icon: '➕', desc: 'Cuộc hội thoại mới'", "'/new', icon: '➕', desc: 'New conversation'"),
    ("'/upload', icon: '📤', desc: 'Tải lên hợp đồng'", "'/upload', icon: '📤', desc: 'Upload contract'"),
    ("Tìm kiếm luật, hợp đồng, lệnh...", "Search laws, contracts, commands..."),
    ("category: 'Lệnh'", "category: 'Commands'"),
    ("Xem hợp đồng", "View contracts"),
    ("Đổi giao diện sáng/tối", "Toggle light/dark theme"),
    ("Không tìm thấy hợp đồng", "No contracts found"),
    ("Không tìm thấy cuộc hội thoại", "No conversations found"),
    ("Cuộc hội thoại", "Conversation"),
    (" tin", " msgs"),
    ("Lệnh", "Commands"),
    ("📄 Xem", "📄 View"),
    ("🔍 Rà soát", "🔍 Review"),
    ("'điều'", "'section'"),
    ("'luật'", "'law'"),
    ("'nghị định'", "'ordinance'"),
    ("'thông tư'", "'circular'"),
    ("'hợp đồng'", "'contract'"),
    ("'rà soát'", "'review'"),
    ("'rủi ro'", "'risk'"),
    ("'phân tích'", "'analyze'"),
    ("'liệt kê'", "'list'"),
    ("'danh sách'", "'list'"),
    ("'soạn'", "'draft'"),
    ("'tạo'", "'create'"),
    ("'mẫu'", "'template'"),
    ("'xin chào'", "'hello'"),
    ("'giúp gì'", "'help'"),
    ("Phân tích chi tiết hơn", "Analyze in more detail"),
    ("Terms liên quan", "Related terms"),
    ("So sánh với luật cũ", "Compare with previous law"),
    ("Xuất ra Word", "Export to Word"),
    ("Đề xuất sửa đổi", "Suggest revisions"),
    ("Xuất báo cáo rà soát", "Export review report"),
    ("So sánh hợp đồng khác", "Compare with another contract"),
    ("Phân tích chi tiết rủi ro", "Detailed risk analysis"),
    ("Rà soát tất cả hợp đồng", "Review all contracts"),
    ("Analytics hợp đồng", "Contract analytics"),
    ("Chỉnh sửa thêm", "Edit further"),
    ("Rà soát lại", "Review again"),
    ("Rà soát hợp đồng", "Review contract"),
    ("Tạo văn bản mới", "Create new document"),
    ("Liệt kê hợp đồng", "List contracts"),
    ("Tóm tắt ngắn gọn", "Brief summary"),
    (" sắp hết hạn (", " expiring soon ("),
    (" ngày)", " days)"),
    ("Kiểm tra hợp đồng ", "Check contract "),
    (" sắp hết hạn", " expiring soon"),
    (" đã hết hạn ", " expired "),
    ("Hợp đồng ", "Contract "),
    (" đã hết hạn, cần xử lý gì?", " has expired — what should I do?"),
    (" hợp đồng chưa được rà soát", " contracts not yet reviewed"),
    ("Rà soát tất cả hợp đồng chưa được kiểm tra", "Review all unreviewed contracts"),
    ("🔔 Thông báo", "🔔 Notifications"),
    ("Không có thông báo mới", "No new notifications"),
    ("Đang xử lý...", "Processing..."),
    ("Không có cảnh báo rủi ro 🎉", "No risk alerts 🎉"),
    ("Đã hết hạn ", "Expired "),
    ("Còn ", "Remaining "),
    (" câu hỏi", " questions"),
    ("Không thể tải dữ liệu từ server", "Could not load data from server"),
    ("Đang tạo báo cáo...", "Generating report..."),
    ("Lỗi tạo báo cáo", "Report generation error"),
    ("Đã tải báo cáo!", "Report downloaded!"),
    ("Update hồ sơ công ty", "Update company profile"),
    ("Thêm tên, mã số thuế, địa chỉ", "Add name, tax ID, address"),
    ("Upload hợp đồng đầu tiên", "Upload your first contract"),
    ("Tải lên để AI rà soát", "Upload for AI review"),
    ("Upload tài liệu nội bộ", "Upload internal documents"),
    ("Văn bản, quy định, nội quy", "Documents, policies, regulations"),
    ("Chat với AI lần đầu", "Chat with AI for the first time"),
    ("Hỏi bất kỳ câu hỏi pháp lý nào", "Ask any legal question"),
    ("Mời thành viên", "Invite team members"),
    ("Thêm đồng nghiệp vào nhóm", "Add colleagues to your team"),
    ("✅ Hoàn thành", "✅ Done"),
    ("Tính năng sắp ra mắt", "Feature coming soon"),
    ("Chưa có ghi chú", "No notes yet"),
    ("Đã lưu ghi chú", "Note saved"),
    ("Lỗi lưu ghi chú", "Error saving note"),
    ("Đã đánh dấu hoàn thành", "Marked as complete"),
    ("Lỗi cập nhật ghi chú", "Error updating note"),
    ("Đã xóa ghi chú", "Note deleted"),
    ("Lỗi xóa ghi chú", "Error deleting note"),
    ("📝 Ghi chú", "📝 Notes"),
    ("+ Thêm", "+ Add"),
    ("🎯 Cần làm", "🎯 Action item"),
    ("Nhập ghi chú...", "Enter note..."),
    ("💾 Lưu", "💾 Save"),
    ("Không có gợi ý mới 🎉", "No new suggestions 🎉"),
    (" hợp đồng đã hết hạn", " contracts expired"),
    ("Cần kiểm tra và gia hạn hoặc thanh lý", "Review and renew or terminate"),
    (" hợp đồng sắp hết hạn", " contracts expiring soon"),
    ("Trong vòng 30 ngày tới", "Within the next 30 days"),
    ("Chưa có hợp đồng nào", "No contracts yet"),
    ("Upload hợp đồng đầu tiên để bắt đầu", "Upload your first contract to get started"),
    ("Mọi thứ đang tốt!", "Everything looks good!"),
    ("Không có cảnh báo nào cần chú ý", "No alerts need attention"),
    ("# Cuộc hội thoại - AI Legal Agent", "# Conversation - AI Legal Agent"),
    ("Xuất lúc: ", "Exported at: "),
    ("Rà soát hoàn tất!", "Review complete!"),
    ("Lỗi khi rà soát: ", "Review error: "),
    ("Không rõ", "Unknown"),
    ("Đang phân tích...", "Analyzing..."),
    # Calendar headers
    ('<div class="cal-day-header">CN</div>', '<div class="cal-day-header">Sun</div>'),
    ('<div class="cal-day-header">T2</div>', '<div class="cal-day-header">Mon</div>'),
    ('<div class="cal-day-header">T3</div>', '<div class="cal-day-header">Tue</div>'),
    ('<div class="cal-day-header">T4</div>', '<div class="cal-day-header">Wed</div>'),
    ('<div class="cal-day-header">T5</div>', '<div class="cal-day-header">Thu</div>'),
    ('<div class="cal-day-header">T6</div>', '<div class="cal-day-header">Fri</div>'),
    ('<div class="cal-day-header">T7</div>', '<div class="cal-day-header">Sat</div>'),
    # test-stream
    ("'Xin chào'", "'Hello'"),
    # manifest
    ("Trợ lý pháp lý AI cho doanh nghiệp Việt Nam", "AI legal assistant for India businesses"),
]

# Second pass: fix partial/mixed replacements (longest first)
FIXUP = [
    ("499K<span class=\"currency\">đ</span>", "₹4,999<span class=\"currency\"></span>"),
    ("Delete tất cả contracts đã removed >30 days?", "Delete all soft-deleted contracts older than 30 days?"),
    ("＋ Tải lên contracts", "＋ Upload contract"),
    ("So sánh contracts", "Compare contracts"),
    ("View rủi ro contracts", "View contract risks"),
    ("Phân tích contracts lao động của tôi", "Analyze my employment contract"),
    ("⚖️ Phân tích contracts lao động", "⚖️ Analyze employment contract"),
    ("Liệt kê tất cả contracts đang có", "List all my contracts"),
    ("📋 Liệt kê contracts", "📋 List contracts"),
    ("Soạn contracts dịch vụ", "Draft a service agreement"),
    ("✍️ Soạn contracts dịch vụ", "✍️ Draft service agreement"),
    ("Tải lên contracts", "Upload contract"),
    ("File contracts (PDF, DOCX, hoặc ảnh)", "Contract file (PDF, DOCX, or image)"),
    ("Loại contracts", "Contract type"),
    ("Contracts lao động", "Employment contract"),
    ("Contracts dịch vụ", "Service contract"),
    ("Contracts thuê", "Lease contract"),
    ("Contracts mua bán", "Sale contract"),
    ("Contracts hợp tác", "Partnership contract"),
    ("Chi tiết contracts", "Contract details"),
    ("💾 Save thông msgs", "💾 Save profile"),
    ("💾 Save công ty", "💾 Save company"),
    ("💾 Save thông báo", "💾 Save notifications"),
    ("🔗 Connected với OpenAI", "🔗 Connect with OpenAI"),
    ("🔗 Connected với Google", "🔗 Connect with Google"),
    ("💾 Save cấu hình", "💾 Save configuration"),
    ("📄 Xuất contracts", "📄 Export contracts"),
    ("📦 Upload nhiều contracts", "📦 Batch upload contracts"),
    ("'hanh_chinh': 'Hành chính', 'noi_bo': 'Nội bộ'", "'hanh_chinh': 'Administrative', 'noi_bo': 'Internal'"),
    ("'Đọc contracts'", "'Read contract'"),
    ("'Liệt kê contracts'", "'List contracts'"),
    ("'So sánh contracts'", "'Compare contracts'"),
    ("Chưa có contracts", "No contracts yet"),
    ("Rà soát Contracts", "Contract Review"),
    ("Kết quả tìm kiếm sẽ hiển thị ở đây", "Search results will appear here"),
    ("Kết quả tìm kiếm", "Search results"),
    ("📋 Nhật ký", "📋 Audit log"),
    ("Kích thước:", "Size:"),
    ("Loại:", "Type:"),
    (" contracts đã chọn", " contracts selected"),
    ("Bỏ chọn", "Clear selection"),
    ("⚖️ So sánh", "⚖️ Compare"),
    ("Hiệu lực", "Active"),
    ("Sắp hết hạn", "Expiring soon"),
    ("Hết hạn", "Expired"),
    ("Bên liên quan", "Parties"),
    ("Kết thúc", "End date"),
    ("Giá trị", "Value"),
    ("Kéo thả hoặc bấm để upload", "Drag & drop or click to upload"),
    ("Tối đa 10MB", "Max 10MB"),
    ("Chưa có API key nào.", "No API keys yet."),
    ("➕ Tạo API Key", "➕ Create API Key"),
    ("Ví dụ sử dụng", "Usage examples"),
    ("Thời hạn thử việc tối đa?", "What is the maximum probation period?"),
    ("AI phân tích rủi ro, điều khoản, và tuân thủ pháp luật India", "AI analyzes risks, clauses, and India law compliance"),
    ("Kéo thả file hoặc bấm để chọn", "Drag & drop a file or click to choose"),
    ("Hỗ trợ: PDF, DOCX, DOC • Tối đa 50MB", "Supported: PDF, DOCX, DOC • Max 50MB"),
    ("— hoặc —", "— or —"),
    ("Dán nội dung contracts vào đây...", "Paste contract content here..."),
    ("MỨC ĐỘ RỦI RO TỔNG THỂ", "OVERALL RISK LEVEL"),
    ("Terms cần lưu ý", "Clauses to note"),
    ("Terms thiếu", "Missing clauses"),
    ("Tuân thủ pháp luật", "Legal compliance"),
    ("Khuyến nghị", "Recommendations"),
    ("Đang tải mẫu văn bản...", "Loading templates..."),
    (" lần sử dụng", " uses"),
    ("title=\"Rà soát\"", "title=\"Review\""),
    ("title=\"Phân tích\"", "title=\"Analyze\""),
    ("Chỉ hỗ trợ file PDF, DOC, DOCX", "Only PDF, DOC, DOCX files supported"),
    ("File không được vượt quá 50MB", "File must not exceed 50MB"),
    ("Đã chọn file:", "File selected:"),
    ("Vui lòng chọn file hoặc nhập nội dung contracts", "Please choose a file or enter contract content"),
    ("7 days trước", "Last 7 days"),
    ("'hop_dong_lao_dong': 'Lao động', 'hop_dong_dich_vu': 'Dịch vụ', 'hop_dong_thue': 'Thuê', 'hop_dong_mua_ban': 'Mua bán', 'hop_dong_hop_tac': 'Hợp tác'", "'hop_dong_lao_dong': 'Employment', 'hop_dong_dich_vu': 'Service', 'hop_dong_thue': 'Lease', 'hop_dong_mua_ban': 'Sale', 'hop_dong_hop_tac': 'Partnership'"),
    ("|| 'Thấp'", "|| 'Low'"),
    ("📄 Contracts gốc", "📄 Original contract"),
    ("'None dữ liệu'", "'No data'"),
    ("{ low: 'Thấp', medium: 'Trung bình', high: 'Cao' }", "{ low: 'Low', medium: 'Medium', high: 'High' }"),
    ("Đã tải báo cáo", "Report downloaded"),
    ("Delete contracts này?", "Delete this contract?"),
    ("Đã removed", "Deleted"),
    ("Features đang phát triển", "Feature in development"),
    ("AI đã phân tích xong!", "AI analysis complete!"),
    ("Đã tải lên!", "Uploaded!"),
    ("Không thể tải lên", "Upload failed"),
    ("Phân tích AI", "AI Analysis"),
    ("Phân tích hoàn tất!", "Analysis complete!"),
    ("Delete tài liệu này?", "Delete this document?"),
    ("Phân tích văn bản:", "Analyze document:"),
    ("Đang tìm...", "Searching..."),
    ("Không tìm thấy results", "No results found"),
    ("Lỗi tìm kiếm", "Search error"),
    ("Lỗi kết nối", "Connection error"),
    ("Giải thích ", "Explain "),
    (" của ", " of "),
    ("Giải thích về ", "Explain "),
    ("Tối đa 5 contracts", "Maximum 5 contracts"),
    ("Chọn ít nhất 2 contracts", "Select at least 2 contracts"),
    ("⚖️ Đang so sánh ", "⚖️ Comparing "),
    ("So sánh: ", "Compare: "),
    ("Không thể so sánh", "Could not compare"),
    ("📋 Tóm tắt so sánh", "📋 Comparison summary"),
    ("📋 Phân tích so sánh", "📋 Comparison analysis"),
    ("🏆 Contracts có lợi nhất", "🏆 Best contract for company"),
    ("🔍 Điểm khác biệt", "🔍 Key differences"),
    ("⚠️ Điểm không nhất quán", "⚠️ Inconsistencies"),
    ("✅ Điểm mạnh", "✅ Strengths"),
    ("❌ Điểm yếu", "❌ Weaknesses"),
    (" cần chú ý)", " need attention)"),
    ("Quá hạn ", "Overdue by "),
    (" ngày", " days"),
    ("Hết hạn hôm nay!", "Expires today!"),
    ("HĐ expiring soon", "contracts expiring soon"),
    ("🔍 Phân tích AI", "🔍 AI Analysis"),
    ("💬 Ghi chú", "💬 Notes"),
    ("💬 Bình luận", "💬 Comment"),
    ("⚠️ Vấn đề", "⚠️ Issue"),
    ("🔖 Đánh dấu", "🔖 Highlight"),
    ("'Bạn'", "'You'"),
    ("Ghi chú cho:", "Note for:"),
    ("Đã thêm ghi chú", "Note added"),
    ("Không thể thêm ghi chú", "Could not add note"),
    ("Đã removed ghi chú", "Note deleted"),
    ("Đã lưu thông msgs cá nhân", "Profile saved"),
    ("Đã lưu thông msgs công ty", "Company info saved"),
    ("Settings saved thông báo", "Notification preferences saved"),
    ("Đã xuất tất cả dữ liệu", "All data exported"),
    ("Đã xuất lịch sử chat", "Chat history exported"),
    ("Đã xuất dữ liệu contracts", "Contract data exported"),
    ("Vui lòng nhập API Key", "Please enter an API key"),
    ("Đang lưu...", "Saving..."),
    ("✅ Đã lưu & kết nối thành công", "✅ Saved & connected successfully"),
    ("Đã lưu cấu hình AI Provider", "AI Provider configuration saved"),
    ("Không thể lưu cấu hình", "Could not save configuration"),
    ("Vui lòng nhập API Key trước", "Please enter an API key first"),
    ("Đang kiểm tra...", "Testing..."),
    ("✅ Connected thành công", "✅ Connected successfully"),
    ("LLM Provider hoạt động tốt!", "LLM Provider is working!"),
    ("OAuth cho ${provider} chưa được triển khai. Vui lòng nhập API Key thủ công.", "OAuth for ${provider} is not implemented yet. Please enter an API key manually."),
    (" (đã lưu)", " (saved)"),
    ("Key đã được lưu và mã hóa trên server", "Key is saved and encrypted on the server"),
    ("✅ Đã kết nối — ", "✅ Connected — "),
    ("Đã dừng", "Stopped"),
    ("Đang suy nghĩ...", "Thinking..."),
    ("'/so-sanh'", "'/compare'"),
    ("'/review', icon: '🔍', desc: 'Rà soát contracts'", "'/review', icon: '🔍', desc: 'Review contract'"),
    ("useSuggestion('Rà soát contracts')", "useSuggestion('Review contract')"),
    ("Tìm kiếm luật, contracts, lệnh...", "Search laws, contracts, commands..."),
    ("Không tìm thấy contracts", "No contracts found"),
    ("/ tra cứu luật · @ open contract · ? find chat", "/ search law · @ open contract · ? find chat"),
    ("Export reports rà soát", "Export review report"),
    ("So sánh contracts khác", "Compare with another contract"),
    ("Rà soát tất cả contracts", "Review all contracts"),
    ("Rà soát contracts", "Review contract"),
    ("Liệt kê contracts", "List contracts"),
    ("Kiểm tra contracts ", "Check contract "),
    (" contracts chưa được rà soát", " contracts not yet reviewed"),
    ("Rà soát tất cả contracts chưa được kiểm tra", "Review all unreviewed contracts"),
    ("None thông báo mới", "No new notifications"),
    ("None cảnh báo rủi ro 🎉", "No risk alerts 🎉"),
    ("Upload contracts đầu tiên", "Upload your first contract"),
    ("Hỏi bất kỳ questions pháp lý nào", "Ask any legal question"),
    ("Features sắp ra mắt", "Feature coming soon"),
    ("Lỗi removed ghi chú", "Error deleting note"),
    ("None gợi ý mới 🎉", "No new suggestions 🎉"),
    (" contracts đã hết hạn", " contracts expired"),
    ("Trong vòng 30 days tới", "Within the next 30 days"),
    ("Chưa có contracts nào", "No contracts yet"),
    ("Upload contracts đầu tiên để bắt đầu", "Upload your first contract to get started"),
]

FILES = [
    ROOT / "index.html",
    ROOT / "app.html",
    ROOT / "platform-admin.html",
    ROOT / "test-stream.html",
    ROOT / "manifest.json",
]


def translate_file(path: Path) -> int:
    text = path.read_text(encoding="utf-8")
    original = text
    for vi, en in TRANSLATIONS:
        text = text.replace(vi, en)
    for vi, en in FIXUP:
        text = text.replace(vi, en)
    if text != original:
        path.write_text(text, encoding="utf-8")
    return sum(1 for a, b in zip(original, text) if a != b)  # rough change indicator


def count_vietnamese(text: str) -> int:
    import re
    return len(re.findall(r"[àáảãạăắằẳẵặâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵđĐ]", text))


def main():
    for f in FILES:
        if not f.exists():
            print(f"SKIP {f}")
            continue
        before = count_vietnamese(f.read_text(encoding="utf-8"))
        translate_file(f)
        after = count_vietnamese(f.read_text(encoding="utf-8"))
        print(f"{f.name}: {before} -> {after} Vietnamese chars remaining")


if __name__ == "__main__":
    main()
